# Generated by Django 4.2.7 on 2023-11-09 07:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('gid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('natemis', models.IntegerField()),
                ('school', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=15)),
                ('phase', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='observations',
            name='diss_oxygen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='diss_oxygen_unit',
            field=models.CharField(blank=True, choices=[('mgl', 'mg/l'), ('%DO', '%DO'), ('PPM', 'PPM'), ('na', 'Unknown')], default='mgl', max_length=8),
        ),
        migrations.AlterField(
            model_name='observations',
            name='elec_cond',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='elec_cond_unit',
            field=models.CharField(blank=True, choices=[('S/m', 'S/m'), ('µS/cm', 'µS/cm'), ('mS/m', 'mS/m'), ('na', 'Unknown')], default='mS/m', max_length=8),
        ),
        migrations.AlterField(
            model_name='observations',
            name='flag',
            field=models.CharField(choices=[('dirty', 'Dirty'), ('clean', 'Clean')], default='dirty', max_length=5),
        ),
        migrations.AlterField(
            model_name='observations',
            name='gid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observations',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='monitor.sites'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='water_clarity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='water_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='org_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('ngo', 'NGO'), ('conservancy', 'Conservancy'), ('private', 'Private citizen'), ('government', 'Government department')], max_length=11),
        ),
        migrations.AlterField(
            model_name='sites',
            name='gid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sites',
            name='river_cat',
            field=models.CharField(blank=True, choices=[('rocky', 'Rocky'), ('sandy', 'Sandy')], max_length=5),
        ),
        migrations.AlterModelTable(
            name='observations',
            table='observations',
        ),
        migrations.AlterModelTable(
            name='organisations',
            table='organisations',
        ),
        migrations.AlterModelTable(
            name='sites',
            table='sites',
        ),
    ]
