# Generated by Django 4.2.7 on 2023-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_schools_alter_observations_diss_oxygen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='diss_oxygen_unit',
            field=models.CharField(blank=True, choices=[('mgl', 'mg/l'), ('%DO', '%DO'), ('PPM', 'PPM'), ('na', 'Unknown')], default='mgl', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='elec_cond_unit',
            field=models.CharField(blank=True, choices=[('S/m', 'S/m'), ('µS/cm', 'µS/cm'), ('mS/m', 'mS/m'), ('na', 'Unknown')], default='mS/m', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='flag',
            field=models.CharField(choices=[('dirty', 'Dirty'), ('clean', 'Clean')], default='dirty', max_length=5, null=True),
        ),
    ]
