# Generated by Django 4.2.7 on 2023-12-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_schools_alter_observations_diss_oxygen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sites',
            name='miniSass_ML_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='miniSass_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='ml_model_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='ml_model_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='site_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/'),
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='sites',
            name='assessment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.assessment'),
        ),
    ]
