# Generated by Django 4.2.7 on 2023-12-07 08:00

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_schools_alter_observations_diss_oxygen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/minio', location='/home/web/minio'), upload_to=monitor.models.site_image_path)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.sites')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationPestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/minio', location='/home/web/minio'), upload_to=monitor.models.observation_pest_image_path)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.observations')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.pest')),
            ],
        ),
    ]
