# Generated by Django 4.2.7 on 2023-12-08 23:56

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_pest_and_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationpestimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/minio-media', location='/home/web/minio'), upload_to=monitor.models.observation_pest_image_path),
        ),
        migrations.AlterField(
            model_name='observations',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='monitor.sites'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/minio-media', location='/home/web/minio'), upload_to=monitor.models.site_image_path),
        ),
    ]
