# Generated by Django 4.2.7 on 2023-12-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_pest_and_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='observations',
            name='minisass_ml_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observations',
            name='ml_model_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='observations',
            name='ml_model_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.assessment'),
        ),
    ]
