# Generated by Django 4.2.7 on 2023-12-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_observationpestimage_image_and_more'),
        ('monitor', '0004_assessment_observations_minisass_ml_score_and_more'),
    ]

    operations = [
    ]
