# Generated by Django 4.2.7 on 2024-01-14 23:46

from django.db import migrations, models
import django.db.models.deletion
from minisass.models import GroupScores as OldGroupScores
db_field_dict = {a[0]: a[0] for a in OldGroupScores.DB_FIELDS}


def populate_group(apps, schema_editor):
    ObservationPestImage = apps.get_model('monitor', 'ObservationPestImage')
    GroupScores = apps.get_model('minisass', 'GroupScores')

    for image in ObservationPestImage.objects.all():
        key = db_field_dict.get(image.pest.name.lower().replace(' ', '_'), '')
        if image.pest.name.lower() == 'bugs or beetles':
            key = 'bugs_beetles'
        elif image.pest.name.lower() == 'crabs or shrimps':
            key = 'crabs_shrimps'
        elif image.pest.name.lower() == 'flat worms':
            key = 'flatworms'
        groups = GroupScores.objects.filter(db_field=key)
        if groups.exists():
            image.group = groups.first()
            image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('minisass', '0006_mobileapp'),
        ('monitor', '0007_alter_observationpestimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationpestimage',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minisass.groupscores'),
        ),
        migrations.RunPython(populate_group, lambda a, b: None),
        migrations.AlterField(
            model_name='observationpestimage',
            name='pest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='monitor.pest'),
        ),
    ]
