# Generated by Django 4.2.7 on 2024-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_observationpestimage_pest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='water_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
