# Generated by Django 4.2.7 on 2024-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_observations_ph_alter_observations_water_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='river_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_name',
            field=models.CharField(max_length=50),
        ),
    ]
