# Generated by Django 4.2.7 on 2025-04-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_alter_observationpestimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='country',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
