# Generated by Django 4.2.7 on 2025-05-21 06:58

from django.db import migrations, models
import django.utils.timezone


def populate_submission_date(apps, schema_editor):
    Observations = apps.get_model('monitor', 'Observations')
    observations = Observations.objects.all()
    for observation in observations:
        observation.submission_date = observation.obs_date
        observation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_sites_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(populate_submission_date, lambda a, b: None),
    ]
