# Generated by Django 4.2.7 on 2026-07-28 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import minisass.storage
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_observations_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_a2', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'world country',
                'verbose_name_plural': 'world countries',
            },
        ),
        migrations.AlterField(
            model_name='observationpestimage',
            name='image',
            field=models.ImageField(max_length=250, storage=minisass.storage.minio_storage, upload_to=monitor.models.observation_pest_image_path),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(max_length=250, storage=minisass.storage.minio_storage, upload_to=monitor.models.site_image_path),
        ),
    ]
