version: '3.4'
services:
  dev:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile-dev
    volumes:
      - static-data:/home/web/static
      - media-data:/home/web/media
      - ./django_project:/home/web/django_project
      # Images on the platform will be stored here
      - minio_images:/home/web/minio
    ports:
      # for django test server
      - "5000:8080"
      # for ssh
      - "5001:22"
    entrypoint: [ ]