version: '3.4'
services:
  dev:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    container_name: "${COMPOSE_PROJECT_NAME}_dev"
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/cache:/home/web/cache
    ports:
      # for django test server
      - "5000:8080"
      # for ssh
      - "5001:22"
    entrypoint: [ ]