# Generated by Django 4.2.7 on 2023-12-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisass', '0003_alter_groupscores_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupscores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
