# Generated by Django 4.2.7 on 2023-12-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minisass', '0004_alter_groupscores_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupscores',
            options={'verbose_name_plural': 'Group Scores'},
        ),
    ]
