# Generated by Django 4.2.7 on 2023-12-18 08:27

from django.db import migrations, models
import minisass.models


class Migration(migrations.Migration):

    dependencies = [
        ('minisass', '0005_alter_groupscores_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to=minisass.models.models.mobile_app_path)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
