# Generated by Django 4.2.7 on 2024-01-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisass', '0006_mobileapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
