# Generated by Django 4.2.7 on 2024-01-14 23:58

from django.db import migrations, models
from minisass.models import GroupScores as OldGroupScores


def populate_db_field(apps, schema_editor):
    GroupScores = apps.get_model('minisass', 'GroupScores')
    db_field_dict = {a[0]: a[0] for a in OldGroupScores.DB_FIELDS}
    for gs in GroupScores.objects.all():
        if gs.name.lower() == 'bugs or beetles':
            gs.db_field = 'bugs_beetles'
        elif gs.name.lower() == 'crabs or shrimps':
            gs.db_field = 'crabs_shrimps'
        elif gs.name.lower() == 'flat worms':
            gs.db_field = 'flatworms'
        else:
            gs.db_field = db_field_dict.get(gs.name.lower().replace(' ', '_'), '')
        gs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('minisass', '0006_mobileapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscores',
            name='db_field',
            field=models.CharField(blank=True, choices=[('bugs_beetles', 'bugs_beetles'), ('caddisflies', 'caddisflies'), ('crabs_shrimps', 'crabs_shrimps'), ('damselflies', 'damselflies'), ('dragonflies', 'dragonflies'), ('flatworms', 'flatworms'), ('leeches', 'leeches'), ('minnow_mayflies', 'minnow_mayflies'), ('other_mayflies', 'other_mayflies'), ('snails', 'snails'), ('stoneflies', 'stoneflies'), ('true_flies', 'true_flies'), ('worms', 'worms')], max_length=25),
        ),
        migrations.RunPython(populate_db_field, lambda a, b: None),
    ]
