# Generated by Django 4.2.7 on 2025-07-31 00:26

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('minisass', '0008_privacypolicy_privacypolicyconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedConstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', fernet_fields.fields.EncryptedTextField()),
            ],
            options={
                'verbose_name': 'constance',
                'verbose_name_plural': 'constances',
                'permissions': [('change_config', 'Can change config'), ('view_config', 'Can view config')],
            },
        ),
    ]
