# Generated by Django 4.2.7 on 2023-11-24 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_type', models.CharField(choices=[('School', 'School'), ('NGO', 'NGO'), ('Other', 'Other'), ('University', 'University'), ('Conservancy', 'Conservancy'), ('Private Individual', 'Private Individual'), ('Consultancy', 'Consultancy'), ('Government Department', 'Government Department')], default='Other', max_length=50)),
                ('organisation_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('container', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'container': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minisass_authentication.lookup')),
            ],
        ),
    ]
