# Generated by Django 4.2.5 on 2023-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
