# Generated by Django 4.2.5 on 2023-11-08 03:34
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0002_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='container',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'container': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minisass_authentication.lookup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation_type',
            field=models.ForeignKey(limit_choices_to={'container__description': 'Organisation Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minisass_authentication.lookup'),
        ),
    ]