# Generated by Django 4.2.7 on 2023-12-11 12:59

import django.core.files.storage
from django.db import migrations, models
import minisass_authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0006_userprofile_is_password_enforced_alter_lookup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/minio-media', location='/home/web/minio'), upload_to=minisass_authentication.models.certificate_path),
        ),
    ]
