# Generated by Django 4.2.7 on 2023-12-18 05:40

from django.db import migrations, models


def change_user_profile(apps, schema_editor):
    UserProfile = apps.get_model('minisass_authentication', 'UserProfile')
    for user_profile in UserProfile.objects.all():
        user_profile.expert_approval_status = 'REJECTED'
        if user_profile.expert_approval_status == 'APPROVED' and user_profile.certificate:
            user_profile.is_expert = True
        else:
            user_profile.is_expert = False
        user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0008_userprofile_expert_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expert_approval_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='REJECTED'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_password_enforced',
            field=models.BooleanField(default=True, help_text='Flag whether user has been enforced to use strong password'),
        ),
        migrations.RunPython(change_user_profile, lambda a, b: None)
    ]
