# Generated by Django 4.2.7 on 2025-04-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0010_passwordhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'verbose_name_plural': 'Password Histories'},
        ),
    ]
