# Generated by Django 4.2.7 on 2025-04-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0011_alter_passwordhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upload_preference',
            field=models.CharField(choices=[('wifi', 'Wi-fi Only'), ('mobile', 'Mobile Data Only'), ('both', 'Wi-Fi and Mobile Data')], default='wifi', help_text='Preferred network    type for uploads', max_length=10),
        ),
    ]
