# Generated by Django 4.2.7 on 2024-01-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0011_alter_passwordhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
