# Generated by Django 4.2.7 on 2025-05-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0012_countrymapping'),
        ('minisass_authentication', '0012_userprofile_upload_preference'),
    ]

    operations = [
    ]
