# Generated by Django 4.2.7 on 2025-07-30 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minisass_authentication', '0013_merge_20250505_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='YomaCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code_alpha2', models.CharField(max_length=2, unique=True)),
                ('code_alpha3', models.CharField(max_length=3, unique=True)),
                ('code_numeric', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YomaToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', fernet_fields.fields.EncryptedTextField(help_text='YOMA access token for API requests')),
                ('refresh_token', fernet_fields.fields.EncryptedTextField(blank=True, help_text='YOMA refresh token for obtaining new access tokens', null=True)),
                ('id_token', fernet_fields.fields.EncryptedTextField(blank=True, help_text='YOMA ID token containing user identity information', null=True)),
                ('token_type', models.CharField(default='Bearer', help_text="Type of the access token (usually 'Bearer')", max_length=50)),
                ('expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('refresh_expires_at', models.DateTimeField(blank=True, help_text='When the refresh token expires', null=True)),
                ('scope', models.CharField(blank=True, help_text='OAuth2 scopes granted for this token', max_length=255, null=True)),
                ('session_state', fernet_fields.fields.EncryptedTextField(blank=True, help_text='YOMA session state identifier', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this token record was last updated')),
                ('user', models.OneToOneField(help_text='User associated with this YOMA token', on_delete=django.db.models.deletion.CASCADE, related_name='yoma_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YOMA Token',
                'verbose_name_plural': 'YOMA Tokens',
                'db_table': 'yoma_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
