# Generated by Django 4.2.7 on 2026-07-28 20:54

from django.db import migrations, models
import minisass.storage
import minisass_authentication.models.minisass


class Migration(migrations.Migration):

    dependencies = [
        ('minisass_authentication', '0014_yomacountry_yomatoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, storage=minisass.storage.minio_storage, upload_to=minisass_authentication.models.minisass.certificate_path),
        ),
    ]
