version: '3.9'

services:
   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      volumes:
        - /home/minisass/geoserver_data:/opt/geoserver/data_dir
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
        - EXISTING_DATA_DIR=TRUE
      extra_hosts:
        - "minisass.org:${SERVER_IP_ADDRESS}"
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
