name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy docker-compose.override.template.yml to docker-compose.override.yml
      working-directory: ./deployment
      run: cp docker-compose.override.template.yml docker-compose.override.yml
    - name: Build Docker Compose services
      working-directory: ./deployment
      run: |
        docker compose -p minisass -f docker-compose.yml -f docker-compose.override.yml build --no-cache
